### ISSUE TITLE
Time offsets

### ISSUE THREAD

**Issue by AndyHoggANU** [aidanheerdegen/publish_cosima_data#4]
In some cases, we may want to offset the time before we save the variables. Can a time offset be added as a functionality?

**Comment by aidanheerdegen** [comment]
Added in https://github.com/coecms/splitvar/pull/5

Use the option
```
--offset=auto
```
to reset the time so the first record in the series will be at the time origin as given in the calendar. If the origin needs to be some offset from that in the calendar then pass a number which if the calendar is "days since" is the number of days to subtract from the time axis.

**Comment by AndyHoggANU** [comment]
I am not convinced that we have the right approach for time offsets, but for now I think we should ignore it, and retain the original time from the model simulation.
